name: Frontend CI

on:
  push:
    branches: [ main, setup-cicd ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, setup-cicd ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.7'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build Web
      run: flutter build web
